#!/bin/bash

#SBATCH -n 16                              # Number of cores
#SBATCH --time=16:00:00                    # hours:minutes:seconds
#SBATCH --mem-per-cpu=2000
#SBATCH --tmp=4000                         # per node!!
#SBATCH --gpus=1                           # Ohter options are: --gpus=gtx_1080_ti:1  --gpus=rtx_2080_ti:1
#SBATCH --job-name=gen_job
#SBATCH --output=./jobs/gen_job.out
#SBATCH --error=./jobs/gen_job.err


# env2lmod
#module load gcc/8.2.0 python_gpu/3.10.4 open3d/0.9.0 boost/1.74.0
#conda activate grasp_conda ## change conda name accordingly
#python opt_grasppose.py --exp_name pretrained_male --gender male --pose_ckpt_path pretrained/pretrained_model/male_grasppose_model.pt --object camera --n_object_samples 10


module load gcc/8.2.0 python_gpu/3.10.4 open3d/0.9.0 boost/1.74.0 eth_proxy
source /cluster/scratch/juntuj/venvs/gt/bin/activate
python opt_grasppose.py --exp_name male_16_seq_eat_cam --gender male --pose_ckpt_path pretrained_model/male16_23lbl_seqmodel.pt --object camera --n_object_samples 10 --sample_label 4
python opt_grasppose.py --exp_name male_16_seq_call_cam --gender male --pose_ckpt_path pretrained_model/male16_23lbl_seqmodel.pt --object camera --n_object_samples 10 --sample_label 0
